apiVersion: v1
name: redash
version: 3.1.0-alpha4
appVersion: 24.04.0-dev-b8671264667.25
description: Redash is an open source tool built for teams to query, visualize and collaborate.
keywords:
  - redash
  - analytics
  - visualization
home: https://redash.io/
sources:
  - https://github.com/getredash/redash
icon: https://redash.io/assets/images/elements/redash-logo.svg
maintainers:
  - name: Owen Barton
    email: owen.barton@civicactions.com
engine: gotpl
