apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datareporter.plywood.fullname" . }}
  labels:
    {{- include "datareporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: plywood
spec:
  replicas: {{ .Values.plywood.replicaCount }}
  selector:
    matchLabels:
      {{- include "datareporter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: plywood
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plywood
        {{- include "datareporter.selectorLabels" . | nindent 8 }}
        {{- if .Values.plywood.podLabels }}
        {{- tpl (toYaml .Values.plywood.podLabels) $ | nindent 8 }}
        {{- end }}
      {{- if .Values.plywood.podAnnotations }}
      annotations:
      {{ toYaml .Values.plywood.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datareporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "datareporter.plywood.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "base.images.image" (merge ( dict  "imageRoot" .Values.plywood.image "global" .Values.global  ) . ) }}"
          imagePullPolicy: "{{ include "base.images.pullPolicy" ( dict  "imageRoot" .Values.plywood.image "global" .Values.global  "Values" .Values ) }}"
          ports:
            - name: http
              containerPort: {{ .Values.plywood.server.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
          env:
            - name: PORT
              value: "{{ .Values.plywood.server.port }}"
            {{- toYaml .Values.plywood.env | nindent 12 }}
          resources:
            {{- toYaml .Values.plywood.resources | nindent 12 }}
      {{- with .Values.plywood.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.plywood.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.plywood.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
