{{ range $workerName, $config := .Values.workers -}}
{{- $workerConfig := mergeOverwrite (deepCopy $.Values.worker) $config }}
{{- $context := mergeOverwrite (deepCopy $) (dict "workerName" $workerName)}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.worker.fullname" $context }}
  labels: {{ include "redash.labels" $context | nindent 4 }}
spec:
  replicas: {{ $workerConfig.replicaCount }}
  selector:
    matchLabels: {{ include "redash.selectorLabels" $context | nindent 6 }}
  template:
    metadata:
      labels: {{ include "redash.selectorLabels" $context | nindent 8 }}
      {{- if $workerConfig.podLabels }}
      {{ tpl (toYaml $workerConfig.podLabels) $ | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.podAnnotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      {{ with $.Values.imagePullSecrets -}}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end -}}
      serviceAccountName: {{ include "redash.serviceAccountName" $context }}
      securityContext: {{ toYaml $workerConfig.podSecurityContext | nindent 8 }}
      {{- with concat $.Values.initContainers $workerConfig.initContainers }}
      initContainers: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- with $workerConfig.extraContainers -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ include "redash.name" $context }}-{{ $workerName }}worker
          securityContext: {{ toYaml $workerConfig.securityContext | nindent 12 }}
          image: {{ $.Values.image.registry }}/{{ $.Values.image.repo }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args: 
            - worker
          {{- $volumeMounts := concat $.Values.volumeMounts $workerConfig.volumeMounts }}
          {{- with $volumeMounts }}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end -}}
          {{- with $workerConfig.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- $envCtx := mergeOverwrite (deepCopy $) (dict "Values" (dict "env" $workerConfig.env)) -}}
          {{- include "redash.env" $envCtx | nindent 12 }}
          {{- with (include "redash.envFrom" $) }}
          envFrom: {{ . | nindent 12 }}
          {{- end }}
          {{- with $workerConfig.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- $volumes := concat $.Values.volumes $workerConfig.volumes -}}
      {{- with $volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
